package blackjack;

/**
 * Jack Dickman
 * Blackjack - ShoeTester.java
 */

public class ShoeTester
{
	public static void main(String[] args)
	{
		//         System.out.println("--- NEW SHOE OF 3 DECKS");
		// 
		//         Shoe s = new Shoe(3);
		//         System.out.println(s);
		// 
		//         System.out.println("--- SHUFFLE");
		// 
		//         s.Shuffle();
		//         System.out.println(s);
		// 
		//         System.out.println("--- GET TOP CARD");
		// 
		//         System.out.println(s.dealCard());
		//         System.out.println();
		// 
		//         System.out.println("--- REMOVE TOP CARD");
		// 
		//         System.out.println(s);
		//         
		//         System.out.println("--- DISCARD PILE");
		//         System.out.println(s.getDiscardPile());
		//         System.out.println();

		Shoe shoe = new Shoe(1); 

		System.out.println("DEAL 3 CARDS:");
		System.out.println(shoe.dealCard());
		System.out.println(shoe.dealCard());
		System.out.println(shoe.dealCard());

		System.out.println();

		System.out.println("DISCARD PILE:");
		System.out.println(shoe.getDiscardPile());

		System.out.println();

		System.out.println("SHOE:");
		System.out.println(shoe);

		shoe.reshuffle();

		System.out.println("DISCARD PILE:");
		System.out.println(shoe.getDiscardPile());
	}
}

// OUTPUT:
// 
// --- NEW SHOE OF 3 DECKS
// Ace of Hearts [11]
// Ace of Diamonds [11]
// Ace of Clubs [11]
// Ace of Spades [11]
// King of Hearts [10]
// King of Diamonds [10]
// King of Clubs [10]
// King of Spades [10]
// Queen of Hearts [10]
// Queen of Diamonds [10]
// Queen of Clubs [10]
// Queen of Spades [10]
// Jack of Hearts [10]
// Jack of Diamonds [10]
// Jack of Clubs [10]
// Jack of Spades [10]
// Ten of Hearts [10]
// Ten of Diamonds [10]
// Ten of Clubs [10]
// Ten of Spades [10]
// Nine of Hearts [9]
// Nine of Diamonds [9]
// Nine of Clubs [9]
// Nine of Spades [9]
// Eight of Hearts [8]
// Eight of Diamonds [8]
// Eight of Clubs [8]
// Eight of Spades [8]
// Seven of Hearts [7]
// Seven of Diamonds [7]
// Seven of Clubs [7]
// Seven of Spades [7]
// Six of Hearts [6]
// Six of Diamonds [6]
// Six of Clubs [6]
// Six of Spades [6]
// Five of Hearts [5]
// Five of Diamonds [5]
// Five of Clubs [5]
// Five of Spades [5]
// Four of Hearts [4]
// Four of Diamonds [4]
// Four of Clubs [4]
// Four of Spades [4]
// Three of Hearts [3]
// Three of Diamonds [3]
// Three of Clubs [3]
// Three of Spades [3]
// Two of Hearts [2]
// Two of Diamonds [2]
// Two of Clubs [2]
// Two of Spades [2]
// Ace of Hearts [11]
// Ace of Diamonds [11]
// Ace of Clubs [11]
// Ace of Spades [11]
// King of Hearts [10]
// King of Diamonds [10]
// King of Clubs [10]
// King of Spades [10]
// Queen of Hearts [10]
// Queen of Diamonds [10]
// Queen of Clubs [10]
// Queen of Spades [10]
// Jack of Hearts [10]
// Jack of Diamonds [10]
// Jack of Clubs [10]
// Jack of Spades [10]
// Ten of Hearts [10]
// Ten of Diamonds [10]
// Ten of Clubs [10]
// Ten of Spades [10]
// Nine of Hearts [9]
// Nine of Diamonds [9]
// Nine of Clubs [9]
// Nine of Spades [9]
// Eight of Hearts [8]
// Eight of Diamonds [8]
// Eight of Clubs [8]
// Eight of Spades [8]
// Seven of Hearts [7]
// Seven of Diamonds [7]
// Seven of Clubs [7]
// Seven of Spades [7]
// Six of Hearts [6]
// Six of Diamonds [6]
// Six of Clubs [6]
// Six of Spades [6]
// Five of Hearts [5]
// Five of Diamonds [5]
// Five of Clubs [5]
// Five of Spades [5]
// Four of Hearts [4]
// Four of Diamonds [4]
// Four of Clubs [4]
// Four of Spades [4]
// Three of Hearts [3]
// Three of Diamonds [3]
// Three of Clubs [3]
// Three of Spades [3]
// Two of Hearts [2]
// Two of Diamonds [2]
// Two of Clubs [2]
// Two of Spades [2]
// Ace of Hearts [11]
// Ace of Diamonds [11]
// Ace of Clubs [11]
// Ace of Spades [11]
// King of Hearts [10]
// King of Diamonds [10]
// King of Clubs [10]
// King of Spades [10]
// Queen of Hearts [10]
// Queen of Diamonds [10]
// Queen of Clubs [10]
// Queen of Spades [10]
// Jack of Hearts [10]
// Jack of Diamonds [10]
// Jack of Clubs [10]
// Jack of Spades [10]
// Ten of Hearts [10]
// Ten of Diamonds [10]
// Ten of Clubs [10]
// Ten of Spades [10]
// Nine of Hearts [9]
// Nine of Diamonds [9]
// Nine of Clubs [9]
// Nine of Spades [9]
// Eight of Hearts [8]
// Eight of Diamonds [8]
// Eight of Clubs [8]
// Eight of Spades [8]
// Seven of Hearts [7]
// Seven of Diamonds [7]
// Seven of Clubs [7]
// Seven of Spades [7]
// Six of Hearts [6]
// Six of Diamonds [6]
// Six of Clubs [6]
// Six of Spades [6]
// Five of Hearts [5]
// Five of Diamonds [5]
// Five of Clubs [5]
// Five of Spades [5]
// Four of Hearts [4]
// Four of Diamonds [4]
// Four of Clubs [4]
// Four of Spades [4]
// Three of Hearts [3]
// Three of Diamonds [3]
// Three of Clubs [3]
// Three of Spades [3]
// Two of Hearts [2]
// Two of Diamonds [2]
// Two of Clubs [2]
// Two of Spades [2]
// 
// --- SHUFFLE
// Six of Clubs [6]
// Ace of Clubs [11]
// Queen of Clubs [10]
// Ten of Spades [10]
// Queen of Spades [10]
// Nine of Clubs [9]
// King of Diamonds [10]
// King of Clubs [10]
// Nine of Clubs [9]
// Two of Spades [2]
// Queen of Clubs [10]
// Three of Clubs [3]
// Nine of Diamonds [9]
// Ten of Clubs [10]
// Ace of Clubs [11]
// Two of Spades [2]
// Queen of Hearts [10]
// Seven of Clubs [7]
// Jack of Spades [10]
// Two of Clubs [2]
// Jack of Spades [10]
// Queen of Diamonds [10]
// Ten of Clubs [10]
// Jack of Clubs [10]
// Four of Diamonds [4]
// Ten of Diamonds [10]
// Eight of Diamonds [8]
// Jack of Diamonds [10]
// Two of Clubs [2]
// Seven of Clubs [7]
// Nine of Hearts [9]
// Four of Hearts [4]
// Queen of Hearts [10]
// King of Spades [10]
// Eight of Spades [8]
// Five of Clubs [5]
// Three of Spades [3]
// Ten of Spades [10]
// Nine of Diamonds [9]
// Seven of Diamonds [7]
// Four of Clubs [4]
// Four of Hearts [4]
// Ten of Diamonds [10]
// Nine of Spades [9]
// Four of Diamonds [4]
// Ten of Diamonds [10]
// Jack of Hearts [10]
// Five of Diamonds [5]
// Eight of Clubs [8]
// Seven of Hearts [7]
// Ace of Diamonds [11]
// Five of Diamonds [5]
// Nine of Hearts [9]
// Nine of Diamonds [9]
// Ace of Diamonds [11]
// Three of Hearts [3]
// Six of Hearts [6]
// Jack of Diamonds [10]
// Eight of Hearts [8]
// Seven of Spades [7]
// Six of Spades [6]
// Four of Diamonds [4]
// Three of Clubs [3]
// Two of Spades [2]
// Eight of Hearts [8]
// Queen of Diamonds [10]
// Six of Clubs [6]
// Four of Clubs [4]
// Three of Diamonds [3]
// Two of Diamonds [2]
// Six of Diamonds [6]
// King of Hearts [10]
// King of Spades [10]
// Three of Hearts [3]
// Seven of Spades [7]
// Jack of Clubs [10]
// Ace of Hearts [11]
// Five of Clubs [5]
// Five of Hearts [5]
// Ten of Spades [10]
// Three of Diamonds [3]
// Nine of Spades [9]
// Four of Hearts [4]
// Six of Spades [6]
// Seven of Hearts [7]
// Ten of Hearts [10]
// Five of Spades [5]
// Three of Spades [3]
// King of Diamonds [10]
// Eight of Diamonds [8]
// Five of Clubs [5]
// Jack of Diamonds [10]
// Six of Diamonds [6]
// Four of Spades [4]
// King of Clubs [10]
// Seven of Hearts [7]
// Seven of Diamonds [7]
// Six of Hearts [6]
// Jack of Hearts [10]
// Ace of Spades [11]
// Three of Spades [3]
// Eight of Spades [8]
// Seven of Diamonds [7]
// Two of Diamonds [2]
// King of Clubs [10]
// Two of Hearts [2]
// Two of Hearts [2]
// Six of Clubs [6]
// Two of Hearts [2]
// Queen of Spades [10]
// Six of Spades [6]
// King of Hearts [10]
// Nine of Hearts [9]
// Queen of Spades [10]
// Four of Spades [4]
// Eight of Clubs [8]
// Jack of Hearts [10]
// Queen of Diamonds [10]
// Five of Hearts [5]
// Queen of Hearts [10]
// Ace of Diamonds [11]
// Jack of Clubs [10]
// King of Spades [10]
// Seven of Clubs [7]
// Nine of Spades [9]
// Three of Hearts [3]
// Seven of Spades [7]
// Six of Hearts [6]
// Five of Spades [5]
// King of Hearts [10]
// Ten of Clubs [10]
// Ace of Hearts [11]
// Jack of Spades [10]
// King of Diamonds [10]
// Ace of Clubs [11]
// Ace of Spades [11]
// Nine of Clubs [9]
// Four of Clubs [4]
// Four of Spades [4]
// Three of Diamonds [3]
// Three of Clubs [3]
// Ten of Hearts [10]
// Six of Diamonds [6]
// Two of Diamonds [2]
// Five of Spades [5]
// Eight of Spades [8]
// Two of Clubs [2]
// Queen of Clubs [10]
// Five of Diamonds [5]
// Eight of Clubs [8]
// Eight of Diamonds [8]
// Eight of Hearts [8]
// Ace of Spades [11]
// Five of Hearts [5]
// Ten of Hearts [10]
// Ace of Hearts [11]
// 
// --- GET TOP CARD
// Six of Clubs [6]
// 
// --- REMOVE TOP CARD
// Ace of Clubs [11]
// Queen of Clubs [10]
// Ten of Spades [10]
// Queen of Spades [10]
// Nine of Clubs [9]
// King of Diamonds [10]
// King of Clubs [10]
// Nine of Clubs [9]
// Two of Spades [2]
// Queen of Clubs [10]
// Three of Clubs [3]
// Nine of Diamonds [9]
// Ten of Clubs [10]
// Ace of Clubs [11]
// Two of Spades [2]
// Queen of Hearts [10]
// Seven of Clubs [7]
// Jack of Spades [10]
// Two of Clubs [2]
// Jack of Spades [10]
// Queen of Diamonds [10]
// Ten of Clubs [10]
// Jack of Clubs [10]
// Four of Diamonds [4]
// Ten of Diamonds [10]
// Eight of Diamonds [8]
// Jack of Diamonds [10]
// Two of Clubs [2]
// Seven of Clubs [7]
// Nine of Hearts [9]
// Four of Hearts [4]
// Queen of Hearts [10]
// King of Spades [10]
// Eight of Spades [8]
// Five of Clubs [5]
// Three of Spades [3]
// Ten of Spades [10]
// Nine of Diamonds [9]
// Seven of Diamonds [7]
// Four of Clubs [4]
// Four of Hearts [4]
// Ten of Diamonds [10]
// Nine of Spades [9]
// Four of Diamonds [4]
// Ten of Diamonds [10]
// Jack of Hearts [10]
// Five of Diamonds [5]
// Eight of Clubs [8]
// Seven of Hearts [7]
// Ace of Diamonds [11]
// Five of Diamonds [5]
// Nine of Hearts [9]
// Nine of Diamonds [9]
// Ace of Diamonds [11]
// Three of Hearts [3]
// Six of Hearts [6]
// Jack of Diamonds [10]
// Eight of Hearts [8]
// Seven of Spades [7]
// Six of Spades [6]
// Four of Diamonds [4]
// Three of Clubs [3]
// Two of Spades [2]
// Eight of Hearts [8]
// Queen of Diamonds [10]
// Six of Clubs [6]
// Four of Clubs [4]
// Three of Diamonds [3]
// Two of Diamonds [2]
// Six of Diamonds [6]
// King of Hearts [10]
// King of Spades [10]
// Three of Hearts [3]
// Seven of Spades [7]
// Jack of Clubs [10]
// Ace of Hearts [11]
// Five of Clubs [5]
// Five of Hearts [5]
// Ten of Spades [10]
// Three of Diamonds [3]
// Nine of Spades [9]
// Four of Hearts [4]
// Six of Spades [6]
// Seven of Hearts [7]
// Ten of Hearts [10]
// Five of Spades [5]
// Three of Spades [3]
// King of Diamonds [10]
// Eight of Diamonds [8]
// Five of Clubs [5]
// Jack of Diamonds [10]
// Six of Diamonds [6]
// Four of Spades [4]
// King of Clubs [10]
// Seven of Hearts [7]
// Seven of Diamonds [7]
// Six of Hearts [6]
// Jack of Hearts [10]
// Ace of Spades [11]
// Three of Spades [3]
// Eight of Spades [8]
// Seven of Diamonds [7]
// Two of Diamonds [2]
// King of Clubs [10]
// Two of Hearts [2]
// Two of Hearts [2]
// Six of Clubs [6]
// Two of Hearts [2]
// Queen of Spades [10]
// Six of Spades [6]
// King of Hearts [10]
// Nine of Hearts [9]
// Queen of Spades [10]
// Four of Spades [4]
// Eight of Clubs [8]
// Jack of Hearts [10]
// Queen of Diamonds [10]
// Five of Hearts [5]
// Queen of Hearts [10]
// Ace of Diamonds [11]
// Jack of Clubs [10]
// King of Spades [10]
// Seven of Clubs [7]
// Nine of Spades [9]
// Three of Hearts [3]
// Seven of Spades [7]
// Six of Hearts [6]
// Five of Spades [5]
// King of Hearts [10]
// Ten of Clubs [10]
// Ace of Hearts [11]
// Jack of Spades [10]
// King of Diamonds [10]
// Ace of Clubs [11]
// Ace of Spades [11]
// Nine of Clubs [9]
// Four of Clubs [4]
// Four of Spades [4]
// Three of Diamonds [3]
// Three of Clubs [3]
// Ten of Hearts [10]
// Six of Diamonds [6]
// Two of Diamonds [2]
// Five of Spades [5]
// Eight of Spades [8]
// Two of Clubs [2]
// Queen of Clubs [10]
// Five of Diamonds [5]
// Eight of Clubs [8]
// Eight of Diamonds [8]
// Eight of Hearts [8]
// Ace of Spades [11]
// Five of Hearts [5]
// Ten of Hearts [10]
// Ace of Hearts [11]
// 
// 
// --- DISCARD PILE
// [Six of Clubs [6]]